transparency-dev/merkle

hash_chainer.go
log_verifier.go
log_verifier_test.go

- Makes naming more concise and consistent.
- Use `uint64` for tree sizes and leaf indices.
Part of #3.

Fix names and types in proof verifier

---

compact/nodes.go
proof/proof.go

Avoid the slightly harder to understand loop merging 3 compact ranges.
Instead, use the fact that the first portion of the proof always consists of nodes with
consecutive layers going up to the level at which the ephemeral node is (or would be).
TODO: Add tests for the new `NodeID` navigation functions.

proof: Simplify proof generation further

---

proof/proof.go
proof/proof_test.go

Examples of when information about the ephemeral node can be used:
- Storage engines for Merkle trees that contain ephemeral nodes as
well as immutable ones. In this case `Ephem` can be used to replace
`IDs[begin:end]` before making a query, and then `Rehash` is not
necessary.
- Merkle tree drawing tools. The ephemeral node needs to be displayed,
and sometimes with a style distinct from other nodes.
- Code that needs to extract individual hashes from inclusion and
consistency proofs. The `Nodes` type, with the introduction of `Ephem`
method, provides a complete reflection of the proof.

proof: Add introspection into the ephemeral node

---

compact/range.go
compact/range_test.go

Most uses of compact range invoke the visitor for the leaf node before
the `Append` call. This change makes it the default behaviour of `Append`.
The asymmetry between `Append` and `AppendRange` can be explained by the
fact that `Append` is usually called when the new leaf hasn't been
processed yet, whereas `AppendRange` is usually called when all the nodes
of the compact ranges (as well as nodes below them) have been processed.

compact: Visit the seed node in the Append method

---

compact/nodes.go
compact/nodes_test.go
compact/range.go
compact/range_test.go
proof/proof.go

This change introduces pre-allocation into the `Proof` generation types, thereby
reducing the total number of slice allocations to one. A new helper for computing
the compact range size `compact.RangeSize` is introduced, and the signature of
the previous `compact.RangeNodes` now requires providing a slice to append the
result to.
Part of #3.

proof: Avoid all reallocations

---

proof/proof.go
proof/proof_test.go

The ephemeral node is the node that does not yet exist, and is therefore replaced
by its "children". It can happen that there is only one "child" node representing the
ephemeral node (i.e. when the subtree that it covers is perfect). If this is the case,
we still want to expose this signal to the user of `Proof` type, which can then choose
whether to treat this node as ephemeral or not.
Part of #3.

proof: Allow single child for the ephemeral node

---

compact/range_internal_test.go
compact/range_test.go
testonly/constants.go
testonly/reference_test.go
testonly/tree.go
testonly/tree_test.go

This is a port of in-memory Merkle tree from Trillian. This implementation
will be used both in `merkle` and `trillian` for testing, and can be used by
other packages that need a reference Merkle tree for their tests.
Next steps are:
- Remove this code from Trillian.
- Refactor boilerplate in `merkle` tests which duplicates `testonly.Tree`,
such as in tests for `compact`.

Copy in-memory Merkle tree implementation from Trillian

---

.golangci.yaml
proof/verify_test.go

Will try to set up presubmit integration in subsequent PR.
For now, `golangci-lint run` at least passes locally, which is
still an improvement from before this PR.

Added lint configuration and fixed error

---

.github/workflows/golangci-lint.yml

This gives cleaner integration compared to digging around in cloudbuild output. We still may need to do GCB integration to perform further checks though. https://github.com/golangci/golangci-lint-action

Added lint as action

---

go.mod

We _may_ want to go further than this to support fuzzing (#33), but as an interim go1.17 is sufficiently old that I don't think we'll be excluding anyone by bumping to this.

Update to go1.17

---

compact/node_fuzz_test.go
testonly/tree_fuzz_test.go

Fuzz tests for inclusion and consistency proofs

Fuzz tests for inclusion and consistency proofs

---

compact/testdata/fuzz/FuzzRangeNodes/03167a8f4de6b14a237e918bd96fea8dd45076bd458c8bcf96b09a61df6846ae
compact/testdata/fuzz/FuzzRangeNodes/0e0f7b76aefbacfec1b9d14fb1cf6ddfccbe6772ff60f2ba617fb1b7884df19f
compact/testdata/fuzz/FuzzRangeNodes/13cdadf28017adae88657be24090473325f4db10ab8fa3f22541b7cb10b683b1
compact/testdata/fuzz/FuzzRangeNodes/13dddce380497392cc2a016ad6b881063b6bd99abfd4ffca8ce2781524e43a44
compact/testdata/fuzz/FuzzRangeNodes/2d382dbaf5238a4066cd46a22d5e3d37deeefd23087f7b46aa0352efe2de13a1
compact/testdata/fuzz/FuzzRangeNodes/2e26d182e06aac76b42a5fa546fa288652501b7a8384489e7d2ebbe43290b8b2
compact/testdata/fuzz/FuzzRangeNodes/4502438e2e714833404e371f4ccdffdb472d8ece05d9cd70685d4911671d73a5
compact/testdata/fuzz/FuzzRangeNodes/4b5b8deb6dc0a2aabf73efc8f107f9241a5504cc069224dc666bc2d5ab576f58
compact/testdata/fuzz/FuzzRangeNodes/629ea6f8a4d39bad9b1d45832a75a9b5d81814269fa9ca20e9f9c77e83d78548
compact/testdata/fuzz/FuzzRangeNodes/6365559667f7be67023423270b88fa3cbeb746c81f784f15382a2f66f3a6a151
compact/testdata/fuzz/FuzzRangeNodes/74bfce2710370711bdd53cb9450cb8b84b542b6c0a04b6a02e0cbbdb49e6888e
compact/testdata/fuzz/FuzzRangeNodes/8196e8e5d77a138305dac92e1dae4e651c5da36949f7f9164e26d07d7372bc28
compact/testdata/fuzz/FuzzRangeNodes/88904c8350b849ec832a6b9b5a891c5cbb856afa6d3b9c165ec0c8a011292734
compact/testdata/fuzz/FuzzRangeNodes/b05a02e2727c643c61be18ef3d80944cceec0e779ee8377dfea4e4e47c2d9d48
compact/testdata/fuzz/FuzzRangeNodes/b73cd67a4c77db1aaab5159c2eee5dff74a80e26067a27cfb95832eb0efbf060
compact/testdata/fuzz/FuzzRangeNodes/d92b8ab319960fa968031e6f81ab556df172f913181333c528e98c6ad436578a
compact/testdata/fuzz/FuzzRangeNodes/e32129a7a793ab12790555c46d5a0fb4accddacf1cab7e9bbabca02d71cbbdb7
compact/testdata/fuzz/FuzzRangeNodes/e7b6d88b27442e32ccc06572bb36c824c03427ec1d5dd721b485612f3b55b1ec
compact/testdata/fuzz/FuzzRangeNodes/e8813e9a7cebcf576a05697f95cff9b1f2dfaecf3969ccccec84582165d2747d

Reading and extrapolating from https://go.dev/doc/fuzz/, the Fuzz test will only be fully exercised when a single Fuzz test is run explicitly with the -fuzz parameter to go test. When running go test without this, the Fuzz test will be invoked, but only on the seed corpus. As FuzzRangeNodes did not have a seed corpus, then this test is effectively skipped in our presubmits and CI pipeline.
This change adds the generated corpus from running the fuzz test as the seed corpus. This shouldn't change how well the test is covered when the -fuzz parameter is provided, but does mean that the test will be exercised as part of CI. This seems like a win, but maybe it's bonkers to be submitting generated files?
The generated corpus was acquired with the following commands:
```
go test …
```

Added generated seeds for FuzzRangeNodes

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/build.sh
.clusterfuzzlite/project.yaml
.github/workflows/cflite_build.yml
.github/workflows/cflite_pr.yml

> [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/) is a continuous fuzzing solution that runs as part of Continuous Integration (CI) workflows to find vulnerabilities faster than ever before. With just a few lines of code, **GitHub users can integrate ClusterFuzzLite into their workflow and fuzz pull requests to catch bugs before they are committed**.
Following https://google.github.io/clusterfuzzlite/build-integration/ with bits of https://google.github.io/oss-fuzz/getting-started/new-project-guide/go-lang/#native-go-fuzzing-support
Tested:
git clone https://github.com/google/oss-fuzz.git
export PATH_TO_PROJECT=$HOME/merkle
python3 infra/helper.py build_image --external $PATH_TO_PROJECT
sudo python3 infra/helper.py build_fuzzers --external $PATH_TO_PROJECT
sudo python3 …

ClusterFuzzLite integration and GitHub Actions

---

docs/data_model.md
docs/images/data_model.svg

This change adds some terminology to the docs.

docs: Data model for append-only Merkle trees

---

.github/workflows/codeql-analysis.yml
.github/workflows/go_test.yml

Explicitly mark CodeQL and go_test as read-only.

Tighten action permissions

---

.clusterfuzzlite/build.sh
.github/workflows/cflite_build.yml
.github/workflows/cflite_pr.yml
.github/workflows/codeql-analysis.yml
.github/workflows/go_test.yml
.github/workflows/golangci-lint.yml

Pins our GitHub Action configs and the `clusterfuzzlite` tooling to explicit git hashes.
This reduces the potential for compromised dependencies to undermine our own repo security.

Pin GitHub actions and associated tooling to git hashes

---

.clusterfuzzlite/Dockerfile
.clusterfuzzlite/build.sh

- Use full git hash for tooling pin
- Pin docker image too

More clusterfuzz pinning

---

.golangci.yaml
cloudbuild.yaml

This will be used for presubmit checks

Added cloud build config for merkle

---

.github/dependabot.yml
.github/workflows/govulncheck.yml

Also bump version of go used by vulnerability scanner

Update dependabot weekly instead of daily

---

CHANGELOG.md
proof/verify.go
proof/verify_test.go
testonly/tree_fuzz_test.go

This is useful for other teams in the transparency space and was requested via the transparency-dev Slack channel. The new method is similar in essence to RootFromInclusionProof so fits in within the API.
As noted in the CHANGELOG, this change fixes a logical bug in the previous code that would have successfully verified an _empty_ proof from a tree size of 0 to any other tree size. In this change, trying to verify a consistency from a tree size of 0 to any other size than 0 will be considered an error, no matter what proof is provided.

Support calculating root from consistency proof

---

.clusterfuzzlite/Dockerfile
.github/workflows/go_test.yml
.github/workflows/golangci-lint.yml
.github/workflows/govulncheck.yml
go.mod

Updated lint and vuln checks to pin to the version in go.mod file.

Bump go version to 1.22.7

---

compact/range_test.go
testonly/tree_test.go

The new APIs allow for some cleanup in the common usages we have around uint64. The only downside is that this is go1.22+, but we've already committed to that in the go.mod file.

Switch to math/rand/v2
